alias eno="export NODE_OPTIONS=--max-old-space-size=8192"

alias ga="git add"
alias gbd="git branch --delete"
alias gbdc="git branch --delete \$(git branch | fzf | sed 's/\\* //')"
alias gbD="git branch --delete --force"
alias gbcp="git bc-cherry-pick"
alias gbse="git bc-show-eligible"
alias gc="git commit"
alias gca="git commit --amend"
alias gcan="git commit --amend --no-edit"
alias gcm="git commit -m"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gcoc="git checkout \$(git branch | fzf | sed 's/\\* //')"
alias gcpa="git cherry-pick --abort"
alias gcpc="git cherry-pick --continue"
alias gd="git diff"
alias gds="git diff --staged"
alias gl="git pull"
alias gp="git push"
alias gpf="git push --force"
alias gpu="git push --set-upstream origin HEAD"
alias gst="git status"
alias gwip="git commit --no-verify -m '[WIP]'"
alias gunwip="git log -n 1 | grep -q -c '[WIP]' && git reset HEAD~1"

alias killssh="for pid in \$(ps aux | grep ssh | grep -v grep | awk {'print \$2'}); do kill -9 \$pid; done"
alias krusty="ssh yuryn@krusty"

alias lg="lazygit"

alias ll='ls -lah'

alias ni="npm i"
alias ns="npm start"

alias rb="rush build"
alias rbo="rush build --only"
alias rbt="rush build --to"
alias rf="rush format-all"
alias rr="rush rebuild"
alias rro="rush rebuild --only"
alias rrt="rush rebuild --to"
alias ru="rush update"
alias rxs="rushx start"
alias rxss="rushx storybook:start"
alias rxt="rushx test"
alias rxtu="rushx test:ui"

alias branch="$HOME/work/bright-frontend/common/scripts/deploy-from-branch.sh"
alias cors="$HOME/work/bright-frontend/common/scripts/provision-cors.sh"
alias pr="$HOME/work/bright-frontend/common/scripts/deploy-from-pr.sh"
alias restore="$HOME/work/bright-frontend/common/scripts/restore-backup.sh"
